### ISSUE TITLE
Local txs not sending if they are below min-gas-price

### ISSUE THREAD

**Issue by Hex-Capital** [openethereum/openethereum#496] opened 2021-07-31 00:27 UTC
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: v3.3.0rc4
- **Operating system**: Windows
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

I keep my node at min-gas-price 999000000000 (this is 999 gwei) since I don't care about seeing the mempool. I used to be able to submit txs at any gas price since local txs bypassed the min-gas-price limit. But now my ~30gwei txs do not reach the mempool unless either
1) I lower the min-gas-price to below 30 gwei OR
2) I send at another gasprice higher than min-gas-price

This has only happened since upgrading from v3.2.3 to v3.3.0rc4

FYI I use eth_sendRawTransaction method to send txs

**Comment by sunce86** [comment] 2021-08-01 17:07
What exact error do you get?

**Comment by gituser** [comment] 2021-11-02 11:59
Any update on this issue anyone?

@varasev

**Comment by iFA88** [comment] 2021-11-19 16:13
Noticed, that the transaction where the gasPrice is below the actual block baseFee will not be propagated.

**Comment by iFA88** [comment] 2021-11-21 19:49
`-ltxqueue=trace,own_tx=trace` logging results:
```
2021-11-21 20:27:54  http.worker00 TRACE own_tx  Importing transaction: PendingTransaction { transaction: SignedTransaction { transaction: UnverifiedTransaction { unsigned: Legacy(Transaction { nonce: 2313, gas_price: 78000000000, gas: 21000, action: Call(0xa53857a3931c5b18f9fc42ec243c105f87272906), value: 6240000000000000, data: [] }), signature: SignatureComponents { standard_v: 1, r: 92013966681440102715109973460658076055065802869876154443999098677058329049507, s: 28947670180978235317458111994968652337577197769461621296298348832440253231432 }, chain_id: Some(1), hash: 0x22a86cc73b61cef592dba7667d2153cff09f62f1cf286d1939b71fdea475b655 }, sender: 0x268eb6e0c09790faf4fe70955a6d02933c04673f, public: Some(0xf1e10481d2af4bdabe29e30554e6692551983c689ac36b22c874f6b67a767f43aa3b20e5198430ce30454d3ee52d7311b3fbe9cd192c2ff43dcccf041d7d9c6f) }, condition: None }
2021-11-21 20:27:54  http.worker00 INFO own_tx  Local tx 0x22a86cc73b61cef592dba7667d2153cff09f62f1cf286d1939b71fdea475b655 below minimal gas price accepted
2021-11-21 20:27:54  http.worker00 DEBUG own_tx  Imported to the pool (hash 0x22a86cc73b61cef592dba7667d2153cff09f62f1cf286d1939b71fdea475b655)
2021-11-21 20:27:54  http.worker00 DEBUG txqueue  [0x22a86cc73b61cef592dba7667d2153cff09f62f1cf286d1939b71fdea475b655] Added to the pool.
2021-11-21 20:27:54  http.worker00 DEBUG txqueue  [0x22a86cc73b61cef592dba7667d2153cff09f62f1cf286d1939b71fdea475b655] Sender: 0x268e…673f, nonce: 2313, gasPrice: 78000000000, gas: 21000, value: 6240000000000000, dataLen: 0))
```
That's all log what i got for my txhash.. the transaction still not broadcasted.
Even i don't understand why they think that the transaction is under minimal gas price. `parity_minGasPrice` gives back 1 gwei what i have set.

**Comment by gituser** [comment] 2021-11-21 22:43
@iFA88 

Try setting `-min-gas-price` to a lower value in `[mining]` section, e.g. set min_gas_price to 1 Gwei:

```
[mining]
# Minimum amount of Wei per GAS to be paid for a transaction to be accepted for mining. Overrides --usd-per-tx.
min_gas_price = 1000000000
```

**Comment by lordt4ever** [comment] 2021-11-21 22:52
Ok.

**Comment by iFA88** [comment] 2021-11-22 07:09
@gituser 
I have tried with 1gwei and tried without the parameter, nothing changed.

**Comment by varasev** [comment] 2021-11-22 07:53
I think the reason is that after EIP-1559 activation, the `--min-gas-price` CLI (config) option is responsible for setting min priority fee. If you set --min-gas-price to 1 GWei, a miner node expects that a user should pay at least `1 GWei + baseFee` for gas.

**Comment by iFA88** [comment] 2021-11-22 07:54
@varasev 
Okay, and what happens when i did not set that parameter?

**Comment by iFA88** [comment] 2021-11-22 11:32
Notice: V2 transaction has the same issue.

**Comment by varasev** [comment] 2021-11-22 13:52
@rimrakhimov will look at this issue soon.

**Comment by rimrakhimov** [comment] 2021-11-22 23:32
@iFA88

**Comment by rimrakhimov** [comment] 2021-11-22 23:34
@iFA88 
Could you please provide options you run your client with, and the way you submit the transaction?

**Comment by iFA88** [comment] 2021-11-23 12:46
@rimrakhimov 
I submit the transaction via jsonrpc `eth_sendRawTransaction` method from localhost.
For client parameter have tried lot of combination. The latest was:
```
openethereum --base-path /mnt/data/nodes/eth --chain foundation --tracing on --pruning fast --no-warp --no-ws --no-secretstore --reserved-peers=/mnt/data/nodes/eth/reservedPeers.json --port 3001 --interface 94.199.178.233 --nat=extip:94.199.178.233 --cache-size-db 4096 --cache-size-blocks 64 --cache-size-queue 128 --cache-size-state 1024 --pruning-history 1024 --no-ipc --jsonrpc-port 3000 --jsonrpc-apis all --jsonrpc-server-threads 12 --jsonrpc-allow-missing-blocks --no-persistent-txqueue --tx-queue-no-early-reject --tx-queue-per-sender=128 --refuse-service-transactions --reseal-on-txs=none --log-file /own/logs/nodes/eth/eth.log
```

**Comment by rimrakhimov** [comment] 2021-11-23 14:25
Just to clarify, are you running a client node through which you would like to submit a transaction with the priority fee price lower than min-gas-price set by the node? And the transaction is submitted but is not propagated to other nodes.

Also, did you run `parity_pendingTransactionsStats` call on the node you submitted transaction, or the other client you connected?

**Comment by lordt4ever** [comment] 2021-11-23 23:46
Man I was buying contract eth and bit  wht convid 19 when nothing and
knowledge for future for year 1

**Comment by iFA88** [comment] 2021-11-29 15:21
@rimrakhimov Any other question?

**Comment by rimrakhimov** [comment] 2021-12-06 20:19
@iFA88, sorry for the delay. I've checked the transaction pool. If I got you right, I believe that the behavior you described is still completely valid.

> On the FIRST node my transaction was available in `parity_allTransactionHashes` and `parity_allTransactions`, but in `parity_pendingTransactionsStats` NOT.

`parity_pendingTransactionsStats` returns only transactions that are _pending_ (are ready to be added in the current block). As the transaction you sent has `gasPrice` (v1 legacy transaction) or `maxFeePerGas` (v2 legacy transaction) less than block base fee, it cannot be added into the current block and, thus, is not _pending_.

> The transaction was not available on the SECOND node (not in parity_pendingTransactionsStats and not in parity_allTransactionHashes)

In the current implementation, only transactions that are ready to be added into the block are propagated. So, as the gas transaction is ready to pay is less than the block base fee, it is not propagated. However, the transaction is still kept in the FIRST node's transaction pool, and will be propagated at the moment block base fee becomes less than `gasPrice` or `maxFeePerGas`.



The main difference with v3.2.3 most probably was an introduction of _block base fee_ notation. Before that any transactions were absolutely valid to be added into the next block no matter what gas price they specified. I believe that was the only change occurred. It is still possible to set `--min-gas-price` option to some large value and locally submit a transaction with effective priority gas price lower than `--min-gas-price`, however `maxFeePerGas` value should be greater than current block base fee in order the transaction to be propagated immediately.

**Comment by iFA88** [comment] 2021-12-06 20:26
@rimrakhimov Thank you for your effort.
I think local transaction should propagated at any way even when they are lower as the current/pending block base fee OR even lower as the `--min-gas-price`.
There is any workaround for this or it will be fixed soon?
Thanks!

**Comment by rimrakhimov** [comment] 2021-12-06 20:46
@iFA88, I believe at the moment there is no way to get round block base fee limitation. Regarding fixing it, we will discuss the problem this week, and I will return later with an answer.

**Comment by lordt4ever** [comment] 2021-12-06 22:43
Thanks man..:)

**Comment by varasev** [comment] 2021-12-15 08:13
@rimrakhimov  I tried to make a local test on `posdao-test-setup` and changed the port number on [this line](https://github.com/poanetwork/posdao-test-setup/blob/2faffc1bc3ab1f44c35bebee4bd856db008c2e13/test/01_staking.js#L7) to `8540` instead of `8541` (to make txs go to local rpc `node0`). Transactions sent to port `8540` are not propagated to the local validator nodes for some reason (after block 8 at which EIP-1559 is activated).

If I experimentally set `eip1559Transition` to some later block (say, 28) [here](https://github.com/poanetwork/posdao-test-setup/blob/2faffc1bc3ab1f44c35bebee4bd856db008c2e13/scripts/copy-spec.js#L29), and repeat the experiment, transactions are propagated successfully (until block 28). So, it seems they are not propagated after EIP-1559 is activated.

It seems this happens even if I set `min_gas_price = 0` for all local nodes.

**Comment by rimrakhimov** [comment] 2021-12-15 10:50
@varasev, yes. The node only propagates transactions that are ready to be added into the next block. Before `eip1559Transition` any `gasPrice` was valid if the node was ready to add such a transaction (either `gasPrice >= min_gas_price` or the transaction is local) into the transaction pool. However, after `eip1559Transition` if `gasPrice` is lower than current `baseFee` the transaction cannot be added into the block. That is the reason, why it is not propagated even if `min_gas_price = 0` for all nodes.

**Comment by varasev** [comment] 2021-12-15 11:33
@rimrakhimov Can you please check it yourself locally using `posdao-test-setup`? The gas price seems to be correct there as it is higher than the base fee.

**Comment by rimrakhimov** [comment] 2021-12-15 11:47
@varasev Oh, I see. Will check it

**Comment by varasev** [comment] 2021-12-16 12:00
@rimrakhimov Sorry, everything is fine there. My mistake. The reason was in `eth_sendTransaction` request that was sent to the node which didn't have a key for sender.

**Comment by rimrakhimov** [comment] 2022-01-10 13:27
We decided that the way transaction pool currently works is valid and we are not going to change the implementation. Likewise, it seems, that some other clients (i.e. Geth, Nethermind) work in the same way, thus, changing our implementation may result in other clients rejecting such transactions anyway.

So, I'm closing the issue

**Comment by iFA88** [comment] 2022-01-10 13:41
You are kidding?

To be clear:
You **can not** broadcast a transaction which has lower fee as the actual block base fee.
For example you can not send transaction with 500gwei gasPrice when the actual block has 1200 baseFee.

That is **ridiculous**!

I need a other client (geth) client, that my clients can broadcast his transactions... OMG!

**Comment by varasev** [comment] 2022-01-10 14:05
@iFA88 Can you please reproduce it on https://github.com/poanetwork/posdao-test-setup and write here the steps to reproduce? You can try to send a test transaction to `node0` (which is RPC) when the `baseFee` is higher than your gas price and see if it is mined by some validator's node (`node1`, `node2`, or `node3`) once the `baseFee` reduces to an appropriate value.

**Comment by rimrakhimov** [comment] 2022-01-10 15:03
@iFA88 Could you please clarify a use case that you are using transaction broadcast. I believe, currently if the transaction is local, it will be accepted by the OE node, even though not being broadcasted until actual `baseFee` will become lower than specified `gasPrice`. So, the transaction **should be broadcasted** when it becomes possible to add it into the block. Why do you find such behavior as unacceptable?

**Comment by iFA88** [comment] 2022-01-10 15:08
I'm using simply RPC `eth_sendRawTransaction`.
The main problem, that the node returns the transaction hash as response, like everything is okay. Then this transaction will be STUCK inside the local mem pool and **WILL NOT BE** broadcasted for any peer when the actual block base fee is higher as the transaction gas price.

I thought the issue is clear for you. Almost a high severity issue.

**Comment by iFA88** [comment] 2022-01-10 15:14
For answer to you question is NO.
My client send me the transaction because they will have it to be broadcasted. After that the transaction exists only in my (one of more) client and will may be not propagated for hours/days.
When it happens, that the base fee is lower, then the transaction has **missed** at least one block and may the next block has higher base fee again.
After i restart my client the transaction is gone, because i don't use persistent pending transactions.

I definitely know that other clients propagate transactions which have lower fee as the actual block. That's why i need maintenance a geth to sending new transactions there.. but then why i need openethereum?

**Comment by rimrakhimov** [comment] 2022-01-12 14:19
@iFA88 Ok, I think you are right. I was wrong about other clients. I believe there are two main problems with current transaction pool implementation:

**Comment by iFA88** [comment] 2022-01-12 14:50
@rimrakhimov 
Thank you! Yeah that's my bad, i said clients but i meant partners/customers.
For the second issue:
I think you should not be worried about that, when the node receives a transaction which is below his `--min-gas-price` OR there is more transactions in the mempool which worth more AND the mempool is full THEN the new pending transaction SHOULD be rejected. This test is not easy because there is a lot of transaction in the network and the mempool will be fast full, and there is a bug (related #346 ) when you have too big limit.

**Comment by gituser** [comment] 2022-01-19 15:53
@rimrakhimov any update on this issue?

parity seems to be not broadcasting transactions even if they are local

> @iFA88 Ok, I think you are right. I was wrong about other clients.
> 
> I believe there are two main problems with current transaction pool implementation:
> 
> 1. Local transactions with `maxFeePerGas` (or `gasPrice`) value lower than pending block `baseFee` are not propagated to other clients (even if some clients would accept such transactions into their transaction pools).
> 2. If transaction is not local (i.e. was got from another client propagated it), the transaction will most probably be rejected due to `--min-gas-price` or `--usd-per-tx` parameters set. Transaction will not be rejected only if `--min-gas-price` was explicitly set to zero.
> 
> We will fix the first problem. So, transactions with too low `maxFeePerGas` (or `gasPrice`) will be propagated to other nodes. That way, such transactions will be able to be added into transaction pools of the clients that accepts them (i.e. Geth).
> 
> Fixing the second problem is still under discussion. Before, other OE nodes will reject such transactions, but it should not be a great problem for RPC nodes.

any update on this @rimrakhimov ?

**Comment by rimrakhimov** [comment] 2022-01-24 10:56
@gituser We are working on it. There will be some PR this week available for testing

**Comment by iFA88** [comment] 2022-01-30 21:16
#604 Nice work, let me know when you need testing

**Comment by rimrakhimov** [comment] 2022-02-04 09:48
@iFA88, @gituser If you wish you may try to buid the version from #604, and check whether it works for you and do not introduce any new problems

**Comment by iFA88** [comment] 2022-02-04 15:02
@rimrakhimov
Thanks, i have build your branch and tested it on mainnet.
```
curl --data '{"method":"eth_sendRawTransaction","params":["0x01f866018182843b9aca0082520894610e3b4e804b367c182c5fc4d65d09c0897233898080c080a02502a8983961ee5fff8813b2291ea225afe07267cfe548573fb2503dd6fd1961a03924dd0fe34056fb338cb725c8ce47bde79a9c4ca91d9744fbe26b54ac62dd61"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:3000
{"jsonrpc":"2.0","result":"0x0550b7794260882dad115c8a8d3a9f17c68ae4914fba09929e696cb35f06c279","id":1}
```
I think it is worse than before. `parity_allTransactionHashes` gives many hashes back included my new one, BUT the `parity_pendingTransactionsStats` gives just few hashes back that propagated to ~4 client without my new one. :(

**Comment by rimrakhimov** [comment] 2022-02-04 15:56
@iFA88 Did the transaction eventually achieved your new node (from any other connected client maybe)?

**Comment by iFA88** [comment] 2022-02-04 16:20
Other node did not received my transaction. For comparison  the `parity_pendingTransactionsStats` method gives 2kbyte data with your node, the other (old) node gives 202mb.

**Comment by rimrakhimov** [comment] 2022-02-08 23:46
@iFA88 

1. **Regarding a transaction not reaching the second node.** I have checked PR one more time and I believe that the transaction still is propagated to other nodes at the moment it was submitted to the node. There may be several reasons why you could not find your transaction at the second node.
    
    First, the second node could just reject your transaction when it was broadcast to it. In case your second node runs some of the current OE releases (v.3.3.3 or earlier), the node should be run with option `--max-gas-price=0` for transaction with `gasPrice` lower than current `baseFee` to be accepted by the node. Otherwise, if your second node was also built from this PR, the transaction should specify `maxPriorityFeePerGas` value to be greater than the node `--max-gas-price` option value.
    
    Another reason may be that the transaction did not actually reach the second node. Due to performance requirements, transactions are propagated not to all peers but only to some subset of them (to a squire root of all connected peers to be precise). Ideally, they would accept the transaction and broadcast it further to some subset of their peers. That way, the transaction should eventually reach your second node. However, it may be possible that other nodes your transaction was propagated to either rejected it or accepted it but did not broadcast further (due to too low `gasPrice` value in comparison with current `baseFee`). In that case, your transaction had no chance to reach your second node. The transaction will be propagated again when the `baseFee` value becomes low enough to make your transaction possible to be added into the block (the logic used before this PR applies here).
    
2. **Regarding `parity_pendingTransactionsStats`.** I believe there is a problem with transactions propagation statistics rather than with propagation itself. My hypothesis is the following:
    
    In the prior implementation, the set of transactions statistics was based on the result of previous transactions propagation. That is, when pending transactions propagation occurred, statistics for transactions that were not propagating were removed from the set. That approach allowed not to keep statistics for transactions removed from the pool before EIP-1559. 
    
    After EIP-1559 that approach worked well enough to not notice the problem. Statistics for transactions still in the pool but with `gasPrice` lower than current `baseFee` was also removed from the statistics set and correspondingly from the `parity_pendingTransactionsStats` RPC call result. When the `baseFee` became low enough, the statistics started from scratch, as if the transaction was only received.
    
    In this PR the problem became clear. As now not only pending transactions from the pool are propagated to other peers but also transactions the node recently received. They are propagated independently from pending transactions but still affect the transactions statistics. So, the propagation of new transactions removes statistics for all transactions currently in the pool. That may be the reason why `parity_pendingTransactionsStats` call returns so little data in comparison with prior implementation.
    
    Currently, I think we may just return the behavior `parity_pendingTransactionsStats` had before. That way, it will return statistics for transactions currently in the pool that may be added into the current block. All new transactions will be still propagated to other nodes when imported, but will not be returned with `parity_pendingTransactionsStats`.
    
    In the future, we may add a new RPC call `parity_allTransactionsStats` that will return transaction statistics for all transactions currently in the pool, including the ones with `gasPrice` lower than the current `baseFee`. But, most probably it would be a low priority task, as it seems to require quite big changes while not bringing much functionality.

**Comment by iFA88** [comment] 2022-02-09 13:52
@rimrakhimov 
Thanks for response!

**1.**
I have signed a new transaction with much higher gasPrice and broadcasted to YOUR node:
```
curl --data '{"method":"eth_sendRawTransaction","params":["0xf86581828504a817c80082520894610e3b4e804b367c182c5fc4d65d09c089723389808025a041b0886a1c1c526e8a2f5b8c3c52b2338fefcbfe8f3f155596e48c702170350ba0347bb11e4b1fb8c78a7501440c5ba9fd045f4942e2cef43c63519331319a5fd0"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:3000
{"jsonrpc":"2.0","result":"0x89e3214e86baccb2fcc1b8c5d44d5f8901e3ca3a232bd888fa5baa18f47b1996","id":1}
```
The transaction is available in the same node:
```
curl --data '{"method":"eth_getTransactionByHash","params":["0x89e3214e86baccb2fcc1b8c5d44d5f8901e3ca3a232bd888fa5baa18f47b1996"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:3000
{"jsonrpc":"2.0","result":{"blockHash":null,"blockNumber":null,"chainId":"0x1","condition":null,"creates":null,"from":"0x610e3b4e804b367c182c5fc4d65d09c089723389","gas":"0x5208","gasPrice":"0x4a817c800","hash":"0x89e3214e86baccb2fcc1b8c5d44d5f8901e3ca3a232bd888fa5baa18f47b1996","input":"0x","nonce":"0x82","publicKey":"0x1a449e836a31c1a15b8d1b703d4add7950ea750371e69ee9528e8970ab5eb868ca49158ad6c8aea31d0ba4d15e15a07bc682bee424a6ae9a760475ec5004db08","r":"0x41b0886a1c1c526e8a2f5b8c3c52b2338fefcbfe8f3f155596e48c702170350b","raw":"0xf86581828504a817c80082520894610e3b4e804b367c182c5fc4d65d09c089723389808025a041b0886a1c1c526e8a2f5b8c3c52b2338fefcbfe8f3f155596e48c702170350ba0347bb11e4b1fb8c78a7501440c5ba9fd045f4942e2cef43c63519331319a5fd0","s":"0x347bb11e4b1fb8c78a7501440c5ba9fd045f4942e2cef43c63519331319a5fd0","standardV":"0x0","to":"0x610e3b4e804b367c182c5fc4d65d09c089723389","transactionIndex":null,"type":"0x0","v":"0x25","value":"0x0"},"id":1}
```
Lets see the txpool:

YOUR node:
`parity_allTransactionHashes` has my transaction hash.
`parity_allTransactions` has my transaction.
`parity_localTransactions` has my transaction.
`parity_pendingTransactionsStats` gives nothing about my transaction.
Configuration:
`--no-persistent-txqueue --tx-queue-no-early-reject --tx-queue-per-sender=128 --refuse-service-transactions --reseal-on-txs=none`
`parity_minGasPrice` gives 0x16c990 (1493392) back at the moment.

Other OLD node:
`parity_allTransactionHashes` did not has my transaction hash.
`parity_allTransactions` did not has my transaction.
`parity_pendingTransactionsStats` gives nothing about my transaction.
Configuration:
`--no-persistent-txqueue --tx-queue-no-early-reject --tx-queue-per-sender=128 --refuse-service-transactions --reseal-on-txs=none`
`parity_minGasPrice` gives 0x16b44a (1487946) back at the moment.

Summary the transaction is still **NOT** propagated even with 20gwei gas price. You can even check the etherscan about my tx :)
BTW you can freely use my signed transaction for testing.

**2.**
First of all when the node receives a transaction from local RPC, then should be checked for right nonce and balance (with fee) in the first round. When the transaction is handled like EXTERN (the `--tx-queue-no-unfamiliar-locals` switch what i DONT USE) then must pass the `min-gas-price` condition, after that muss pass the tx pool count/memory condition (there a lower priority transaction should be dropped).
Its a basic error, when the node receives a transaction and does not propagates to the network! When the node has accepted then MUST BE propagated to other nodes. It is an another question, that the other node accepts it or not!

Sadly i can not accept that the `parity_pendingTransactionsStats` doesnt gives the full list back with the statistics. For example the basefee dropping down and (for example) 10 transaction would be propagated, and the next block has again higher basefee where the 10 transaction will be _invisible_ again. This list SHOULD be the same list what the node p2p processor works for propagate.
The `parity_allTransactionHashes` values and `parity_pendingTransactionsStats` keys SET MUST to be EQUAL.


To be sure:
YOUR node: `OpenEthereum/v3.3.3-stable/x86_64-linux-gnu/rustc1.51.0`
Old node: `OpenEthereum/v3.3.0-stable-64a161476-20211117/x86_64-linux-gnu/rustc1.48.0`

**Comment by iFA88** [comment] 2022-02-09 15:42
@rimrakhimov Yes of course, I have sent to mainnet while i write my comment.
The transaction is legacy, so has only gasPrice.
Okay I understand you, when the other node txpool is full and my transaction has lower priority as the lowest in the pool, then will be rejected.
The current lowest gasPrice is 60 gwei in my old node. I will increase now the txpool size and will set some min-gas-price for the old node. So you have right, probably it was rejected. The `parity_allTransactionHashes` has given 
The new configuration for the OLD node:
`--min-gas-price 10000000000 --no-persistent-txqueue --tx-queue-mem-limit 4096 --tx-queue-size 100000 --tx-queue-no-early-reject --tx-queue-per-sender=128 --refuse-service-transactions --reseal-on-txs=none`
I have restarted both node and sent my transaction again.
Sadly everything is the same..
FYI your and the old node are reserved peer for each other and they are connected. Checked with `parity_netPeers` to be sure.

**Comment by iFA88** [comment] 2022-02-09 16:06
I have increased the gasPrice to 60 gwei for my transaction:
```
curl --data '{"method":"eth_sendRawTransaction","params":["0xf8658182850ba43b740082520894610e3b4e804b367c182c5fc4d65d09c08972338980801ca0929138c56ea69116332b5e20e14c33be1160c928140baa0866e0fb2624e37f50a04eea009544513139936d50640bf3c3891f651b034a6b35a58e4763ace3bf64f4"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:3000
{"jsonrpc":"2.0","result":"0x443e97709779e41ba9efbfdbd2cb3c9084403f3f55766d1b0b5864a7cb419f93","id":1}
```
Everything is the same.. my tx wont leave the node..

**Comment by rimrakhimov** [comment] 2022-02-09 16:43
> when the other node txpool is full and my transaction has lower priority as the lowest in the pool, then will be rejected.

That is not quite true. In the old implementation non-local transaction with `effectivePriorityFeePerGas < minGasPrice` will be rejected even if the transaction pool is empty (`effectivePriorityFeePerGas = min(maxPriorityFeePerGas, maxFeePerGas - baseFee)`, or `gasPrice - baseFee` if you send Legacy transaction; subtraction saturates to zero if it results in negative value). So the only way to allow your OLD node to accept incoming transaction is by setting `--min-gas-price=0` option.

Moreover, even in that case it is not guaranteed that the transaction will reach your OLD node. Transactions are broadcast not to all peers, but only to a randomly chosen squire root of all peers due to performance concern. It is assumed, that valid transaction will be accepted by that squire root of peers and broadcast further, propagating the transaction to other peers. However, if all these peers reject your transaction it will not be propagated by them. So imported transaction will be propagated to other peers but still remains only in your transaction pool. The next time the transaction will be propagated is when the `baseFee` drops down to be low enough to make your transaction includable into pending block. 

However, if both of your nodes are mostly connected with nodes that support accepting and broadcasting of transactions with `gasPrice < baseFee` (as far as I know, Geth supports it, but not OpenEthereum or Nethermind), then most probably your transaction will reach your OLD node.

**Comment by iFA88** [comment] 2022-02-09 23:06
You can see, the base fee has fallen under 60 gwei, my transaction was propagated, but the base fee has increased back to higher, so my TX was not included that block.
![image](https://user-images.githubusercontent.com/18205395/153305542-91a912f5-3056-4dd1-accf-b39b85eab71a.png)

**Comment by rimrakhimov** [comment] 2022-02-14 13:23
@iFA88 We've checked the implementation on our net and made sure the propagation of incoming transactions works. You may try to build updated version from these PR and use `parity_newTransactionsStats` which returns the propagation status of all transactions came last 10 blocks. So, that way you may try to see which nodes your transaction was propagated to. Likewise, you may wish to verify that `parity_pendingTransactionsStats` now works as before.

**Comment by iFA88** [comment] 2022-02-14 21:38
It seems the transaction is not really propagated.. No one other see that except my reserved. Etherscan or blockchair did not know anything about that.. :S

**Comment by iFA88** [comment] 2022-02-14 22:46
I waited more than one hours but the transaction has not reached etherscan or blockchair, not even my friends node.
In the list of `parity_allTransactionHashes` was my hash there, but in the `parity_pendingTransactionsStats` not anymore!
I have restarted your node and started the process from the beginning. After `eth_sendRawTransaction` i have see in the `parity_newTransactionsStats` list. Etherscan and my other node finally sees now the transaction.
There was some glitch?!

**Comment by rimrakhimov** [comment] 2022-02-15 05:06
@iFA88 I believe, it was not an OE client problem, as `parity_newTransactionsStats` is only updated when  transaction is actually sent to a peer. Probably, the first time other nodes just rejected your transaction due to some reason (maybe their pools were full at the time and your transaction could not replace any of existing transactions).

**Comment by iFA88** [comment] 2022-02-15 10:53
I have sent again a new transaction with 10gwei (we have now 30gwei basefee) without client restart:
```
curl --data '{"method":"eth_sendRawTransaction","params":["0xf86581848502540be40082520894610e3b4e804b367c182c5fc4d65d09c089723389808026a0494407fcf18d4bd81e514b511f49662dbfd30d6157fdecea29ab6c56ac903797a050e3588ce684fa558dddf5addad008a4a043e5894ab7c35881a3b38279ea103b"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:3000
{"jsonrpc":"2.0","result":"0x70ad8d6a83ed9bc94a0a002e7cf38d7750cf5003a3e186d5b541b11cac3b260b","id":1}
```
On the same node i can see `parity_newTransactionsStats` but NOT in the `parity_pendingTransactionsStats`..
The `parity_newTransactionsStats` says that has been propagated for 47 client. My other node did not received and Etherscan did not knows that TX.
There is definitely a bug, just i dont know what.

I have now restarted your node and sent the TX again, but everything is the same.

**Comment by rimrakhimov** [comment] 2022-02-15 11:59
@iFA88 Could you please share the result of `parity_netPeers` on your node?

**Comment by iFA88** [comment] 2022-02-15 12:07
@rimrakhimov Yeah ofc: https://gist.github.com/iFA88/c0649327892e58c393a5a7a279a99d72

**Comment by rimrakhimov** [comment] 2022-02-16 13:15
@iFA88 `parity_pendingTransactionsStats` should not return anything about your transaction. Currently it only returns statistics for transactions that may be added into the pending block (your's couldn't because of `gasPrice` < `baseFee`).

Regarding your transaction propagation, the fact that your transaction is eventually visible by Etherscan although `baseFee` has not been lower that the transcation `gasPrice` confirms that the transaction has been actually propagated to its peers when the transaction was received. The node propagates a new transaction once for all its peers on transaction receiving. After that, the next time transaction will be propagated is only when the actual block `baseFee` drops below the transaction `gasPrice`. As that has not happened but transaction is available at Etherscan, I assume the following happened: 1) transaction has been propagated to node's peers; 2) most peers rejected your transaction due to too low `gasPrice` (including the nodes of your friends); 3) but at least one of your peers accepted the transaction and broadcast it further; 4) the same thing may happen as in step (2) with other node broadcasting your transactions; 5) eventually, the transaction arrived to the node Etherscan uses to watch for transactions.

**Comment by rimrakhimov** [comment] 2022-02-16 13:38
To sum up, I believe #604 solves the problem described in that issue. It adds the following changes:
2. New transactions are propagated to all peers of the node **once** at the moment the transaction is added into the transaction pool. After that transactions that have `gasPriced` specified to be at least current `baseFee` are broadcast periodically (as they did before).
2. `max_priority_fee_per_gas` value of the transaction is used to compare it with minimal transaction reward the miner would like to accept. Before `effective_priority_fee_per_gas` value was used for that purposes that forced the transaction pool to reject transactions with `priority_fee_per_gas` lower than current `baseFee` value, even though it may be enough to pay the miner the reward it wants in some future - when `baseFee` drops down.
3. New RPC call was added into `parity` namespace to follow propagation statistics for new transactions - `parity_newTransactionsStats`. Currently by default it shows statistics only for transactions that were first seen during the pending block number. The period for which the transaction would be considered `new` may be increased by specifying the number of blocks to keep transactions statistics for via `--new-transactions-stats-period` CLI parameter.

Finally, `parity_pendingTransactionsStats` RPC call has remained the same and does not show statistics for transactions that has `gasPrice` lower than current `baseFee` value, even though such transaction was only received and, thus, propagated to other nodes. That may be considered as a bug, as such transactions still may be considered to be _pending_. I suggest to open a separate issue for that problem, and close this issue when PR #604 will be merged.

**Comment by iFA88** [comment] 2022-02-16 14:20
@rimrakhimov 
Thats bad! Even for debug purposes the `parity_pendingTransactionsStats` should return who has received at least local transaction. At least i think so.
Yeah you have right with that. I'm just wondering why not has your node propagated to my old client who are reserved peers for each other and has min-gas-price zero.
For the first of your sum: Yeah thats a great idea. Then at least the peer propagates so many clients that they have.

Thank you for your time!

**Comment by rimrakhimov** [comment] 2022-02-18 13:54
@iFA88 Unfortunately, I have no explanation why the transaction was not propagated to your old client. I believe it would be just better now to see whether some problems will happen after the release. If some problems arise, new issue may be opened.

**Comment by rimrakhimov** [comment] 2022-02-18 13:56
Created a new issue aiming `parity_pendingTransactionsStats` invalid behavior (#615). The task is considered to have low priority, however. Not sure when it would be done.

Finally, closing this issue

**Closed by rimrakhimov** 2022-02-18 13:56 UTC

**Comment by iFA88** [comment] 2022-02-20 15:52
@rimrakhimov sorry for writing to a closed issue, but may this PR caused an another issue:
I'm using now the latest client `OpenEthereum/v3.3.4-stable-9f87e6dc8-20220218/x86_64-linux-gnu/rustc1.48.0`, and i continuously loosing peers.
I have tried with these and without these parameters too:
`--min-gas-price 10000000000 --tx-queue-mem-limit 64 --tx-queue-size 10000 --reseal-on-txs=none`
Log:
https://gist.github.com/iFA88/3bbb9b01f7bc5dff8d970e1b071fbe57
`parity_allTransactionHashes` gives 9931 hashes back with using that parameters and about 8k without that parameters.

**Comment by rimrakhimov** [comment] 2022-02-20 16:07
@iFA88 could you please run your node with `-l sync=trace` option and share updated logs?

**Comment by iFA88** [comment] 2022-02-20 16:29
@rimrakhimov ofc here is: https://www.fusionsolutions.io/doc/ethNode_2022-02-20_17-24.log

**Comment by varasev** [comment] 2022-02-21 10:25
@iFA88 Did you try setting `--min-peers` option?

**Comment by iFA88** [comment] 2022-02-21 10:28
@varasev no, i did not applied that parameter, but i will try now with `--min-peers=10 --max-peers=50`

**Comment by iFA88** [comment] 2022-02-21 11:41
The logs before the new parameters says, that after 2022-02-21 03:43:40 (UTC) the peers stopped dropping and the node works as expected.
I have now "just" 6607 pending transaction in the node, just clarify i does NOT use the following parameters: `--min-gas-price` `-tx-queue-mem-limit` `--tx-queue-size`

I suspect, that when the node has "MANY" pending transactions, then during propagation the other client (peer) may recognize the many/big size packets (which contains the pending transactions) for flood and dropping my client. The same happens when I set tx-queue limit to high.

Another minor issue: This node runs on a dedicated server where the necessary ports are open, but after 1 hour my peer count peek was JUST 36/50 and average 27.

**Comment by rimrakhimov** [comment] 2022-02-21 14:17
> I suspect, that when the node has "MANY" pending transactions, then during propagation the other client (peer) may recognize the many/big size packets (which contains the pending transactions) for flood and dropping my node.

Number of pending transactions propagated is limited by the maximum number of basic transactions for 4 blocks (currently, 30000000 / 21000 * 4 = 5714) (https://github.com/openethereum/openethereum/blob/main/crates/ethcore/src/client/client.rs#L2733).
I believe that should not be the problem, as the new release did not introduce any modifications to that part of the code.

@iFA88 if you increase the value of `--min-peers` option to 50, for example, will the node increase the number of connected peers till that value after connection establishing is stabilized?

**Comment by iFA88** [comment] 2022-02-21 18:28
So it seems it happens when i have more TX in the pool than 8k. Here is the log with the current parameters: [https://www.fusionsolutions.io/doc/eth_2022-02-21_14-36.log](https://www.fusionsolutions.io/doc/eth_2022-02-21_14-36.log)
I will now apply the `--min-peers 50` and the `-l sync=trace` and will send later the log.

**Comment by iFA88** [comment] 2022-02-21 19:24
Here is: https://www.fusionsolutions.io/doc/eth_2022-02-21_19-29.log
Parameters what i use: 
`--min-gas-price 10000000000 --no-persistent-txqueue --tx-queue-mem-limit 256 --tx-queue-size 10000 --tx-queue-no-early-reject --tx-queue-per-sender=128 --refuse-service-transactions --reseal-on-txs=none -lsync=trace --min-peers 50 --max-peers 50`

**Comment by iFA88** [comment] 2022-02-23 13:15
@rimrakhimov 
> I believe that should not be the problem, as the new release did not introduce any modifications to that part of the code.

Okay, just the #346 is the same issue now. When the tx pool has more than ~8k transaction then the node will continuously loose peers.
