### ISSUE TITLE
2.3.5 can not synchronize to the latest block

### ISSUE THREAD

**Issue by zerochl** [openethereum/openethereum#10462] opened 2019-03-09 04:59 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.3.5
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I found that, the cpu up to 200% before restart, but it down to 80% after restart.

**Comment by zerochl** [comment] 2019-03-09 05:20
I close node by "kill -9",Is that the reason?

**Comment by joshua-mir** [comment] 2019-03-09 07:55
@zerochl this is probably a duplicate of #10371 - can you check that issue out and let me know if you think that is not the case?

Your issue title doesn't appear related to the content of the issue.

**Comment by zerochl** [comment] 2019-03-11 01:45
2019-03-09 12:34:33  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2938 Qed  #7332852   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    4 req/s,   23 µs
2019-03-09 12:34:34  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2938 Qed  #7332852   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    4 req/s,   23 µs
2019-03-09 12:34:34  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2938 Qed  #7332852   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    4 req/s,   23 µs
2019-03-09 12:34:34  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2938 Qed  #7332852   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    4 req/s,   23 µs
2019-03-09 12:34:37  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2938 Qed  #7332852   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   23 µs
2019-03-09 12:35:16  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:16  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:17  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:17  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:17  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:18  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:18  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:18  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:21  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:21  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:21  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:21  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs
2019-03-09 12:35:21  Syncing #7330097 0xa1e3…19ff     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+ 2940 Qed  #7332854   33/50 peers      5 MiB chain  101 MiB db  186 MiB queue    7 MiB sync  RPC: 16 conn,    5 req/s,   25 µs

**Comment by joshua-mir** [comment] 2019-03-19 08:11
@zerochl is the `5 req/s` you are getting over rpc expected? Can you try reducing the number of requests you are making on your node and see if that helps?

**Comment by adria0** [comment] 2020-07-27 15:04
Closing issue due to its stale state.

**Closed by adria0** 2020-07-27 15:04 UTC
Labels: Z1-question 🙋‍♀️
