### ISSUE TITLE
Unable to sync Kotti network for archive node

### ISSUE THREAD

**Issue by APshenkin** [openethereum/openethereum#11633] opened 2020-04-15 11:34 UTC
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version**: v3.0.0-alpha.1
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: no
- **Network**: kotti
- **Restarted**: fresh start 

Parity crashes when try to launch archive Kotti node

```
2020-04-15 11:29:18 UTC Starting OpenEthereum/v3.0.0-alpha.1-nightly-UNKNOWN-UNKNOWN/x86_64-alpine-linux-musl/rustc1.42.0
2020-04-15 11:29:18 UTC Keys path /home/parity/.local/share/io.parity.ethereum//keys/kotti
2020-04-15 11:29:18 UTC DB path /home/parity/.local/share/io.parity.ethereum//chains/kotti/db/717b12a127188bca
2020-04-15 11:29:18 UTC State DB configuration: archive +Fat +Trace
2020-04-15 11:29:18 UTC Operating mode: active
2020-04-15 11:29:18 UTC Configured for Kotti Testnet using Clique engine
2020-04-15 11:29:23 UTC Public node URL: enode://6e2e53312bd8cc5d2f5965521423970adb35737e49d0b6c081cc1e9333a1739458435316fc0ab8830b7e7ee3006dfc75d8934ee88f1ff51ade00cdf48736bde5@172.25.0.7:30303
2020-04-15 11:29:24 UTC Panic occurred, see stderr for details
====================
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
Thread 'Verifier #1' panicked at 'Traces database is incomplete.', /openethereum/ethcore/trace/src/db.rs:248
This is a bug. Please report it at:
    https://github.com/openethereum/openethereum/issues/new
2020-04-15 11:29:24 UTC Block import failed for #4 (0x44b7…4f8f): Parent not found (0x0a45…16aa)
2020-04-15 11:29:24 UTC
Bad block detected: Parent not found
RLP: f9025bf90256a00a45ace630d8783b11eca634ac8a3f4bb8ac126be839a108e08df3cef1b516aaa01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a06dd0a87a91d3e256813d991cd8a0107e279c821e2579f099da7e7d7803a4edd8a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000204839f604080845c489d88b86145544320436f6f706572617469766520417574686f7269747900000000000000b5c77969eb68e1fefa422ab6df588244490608c0715c6b8670b56f22dfb9d45610ad2daccd0baeecc8e2a9ed70bcf7ab61f9bcd9f0e75c4249657d2b5dd2633b00a00000000000000000000000000000000000000000000000000000000000000000880000000000000000c0c0
Header: Header { parent_hash: 0x0a45ace630d8783b11eca634ac8a3f4bb8ac126be839a108e08df3cef1b516aa, timestamp: 1548262792, number: 4, author: 0x0000000000000000000000000000000000000000, transactions_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [69, 84, 67, 32, 67, 111, 111, 112, 101, 114, 97, 116, 105, 118, 101, 32, 65, 117, 116, 104, 111, 114, 105, 116, 121, 0, 0, 0, 0, 0, 0, 0, 181, 199, 121, 105, 235, 104, 225, 254, 250, 66, 42, 182, 223, 88, 130, 68, 73, 6, 8, 192, 113, 92, 107, 134, 112, 181, 111, 34, 223, 185, 212, 86, 16, 173, 45, 172, 205, 11, 174, 236, 200, 226, 169, 237, 112, 188, 247, 171, 97, 249, 188, 217, 240, 231, 92, 66, 73, 101, 125, 43, 93, 210, 99, 59, 0], state_root: 0x6dd0a87a91d3e256813d991cd8a0107e279c821e2579f099da7e7d7803a4edd8, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 10444864, difficulty: 2, seal: [[160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [136, 0, 0, 0, 0, 0, 0, 0, 0]], hash: Some(0x44b74d99e2d6ffa509254c079eab6d89bb6de71d157d9104b513cf0952194f8f) }
Uncles:
Transactions:
2020-04-15 11:29:24 UTC Finishing work, please wait...
2020-04-15 11:29:24 UTC Panic occurred, see stderr for details
====================
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
Thread 'http.worker20' panicked at 'Propagating verifier thread panic on shutdown: Any', /openethereum/ethcore/verification/src/queue/mod.rs:743
This is a bug. Please report it at:
    https://github.com/openethereum/openethereum/issues/new
```

Steps to reporoduce:
```
parity
      --mode active
      --chain kotti
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-cors all
      --ws-interface all
      --ws-origins all
      --ws-hosts all
      --ws-apis web3,eth,net,parity,pubsub,traces
      --base-path /home/parity/.local/share/io.parity.ethereum/
      --fat-db on
      --tracing on
      --no-periodic-snapshot
      --pruning archive
      --logging INFO
      --cache-size 4096
      --db-compaction ssd
```

**Comment by niklasad1** [comment] 2020-04-15 11:55
Closing as duplicate of #11593

Please update the latest master and I think it should be fixed

**Closed by niklasad1** 2020-04-15 11:55 UTC
