### ISSUE TITLE
Feature request: trace information of newest blocks only

### ISSUE THREAD

**Issue by gsalzer** [openethereum/openethereum#10819] opened 2019-06-30 09:38 UTC
Archive nodes provide state and trace information for all blocks, from genesis to the recent block, at the expense of ever increasing disk space (2.7 TB at the moment).
What about a light archive mode that provides this information only for the last N blocks (N configurable) and that acts like the standard mode for older blocks? This would allow us to analyze recent block data with a limited amount of additional disk space, as intermediate state info and traces are removed again from the database after some time.

**Comment by joshua-mir** [comment] 2019-07-01 08:24
Do you think this could be considered a duplicate of this feature request: https://github.com/paritytech/parity-ethereum/issues/9962 @gsalzer?

**Comment by gsalzer** [comment] 2019-07-01 13:36
I'm not sure I fully understand what  #9962 proposes. Setting `pruning_history` to some bigger value does not seem to help for my purpose. `trace_block` requests for even the newest blocks return nothing (`{"jsonrpc":"2.0","result":null,"id":1}`).

It seems that #10760 is more like what I'm looking for. My aim is to get requests like `trace_block` answered for the last 1000 or 10000 blocks. So basically an archive node regarding the last blocks and a normal node for the blocks before.

Maybe I haven't understood the parameters of parity, but the config

```
mode = "active"
warp = false
tracing = "off"
db_compaction = "ssd"
pruning = "fast"
pruning_history=15000
fat_db = "off"
```

does not do what I need. Setting tracing to `on` makes parity want to resync.

**Comment by adria0** [comment] 2020-07-27 15:03
Closing issue due to its stale state.

**Closed by adria0** 2020-07-27 15:03 UTC
Labels: F8-enhancement 🎊, M4-core ⛓
