### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'supplied instant is later than self', library/std/src/time.rs:285

### ISSUE THREAD

**Issue by CamWeston** [openethereum/openethereum#227] opened 2021-01-14 23:24 UTC
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Linux
- **Installation**:  built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

Continue to get this bug every 20 minutes or so while syncing on an i3.xl ec2. 

`====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:597
   2: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:499
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at library/std/src/panicking.rs:495
   5: core::panicking::panic_fmt
             at library/core/src/panicking.rs:92
   6: core::option::expect_failed
             at library/core/src/option.rs:1260
   7: <openethereum::informant::Informant<T> as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::timeout
   8: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
   9: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:71
  13: start_thread
  14: __clone

Thread 'IO Worker #2' panicked at 'supplied instant is later than self', library/std/src/time.rs:285

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new
`

This is my start command
`
nohup ./target/release/openethereum --jsonrpc-interface <redacted> --jsonrpc-hosts="all" --ws-interface <redacted> --ws-hosts="all" --can-restart=true --chain=mainnet &
`

**Comment by yorickdowne** [comment] 2021-01-15 11:52
Duplicate of #169 I think. There's a fix available in PR #193 , which is working well for me so far.

**Comment by roninkaizen** [comment] 2021-01-15 18:34
maybe the db is completely corrupted,
i would also leave the "--can restart" and "--chain=mainnet &"
with a cleanup of the db dir and a restart without the above mentioned settings you should get different results.
and if not, visit us at the discord-channel

**Comment by rakita** [comment] 2021-01-18 08:36
Fix is merged in `dev` branch

**Closed by rakita** 2021-01-18 08:36 UTC
Labels: duplicate
