### ISSUE TITLE
error: could not compile `logos-derive` due to 3 previous errors

### ISSUE THREAD

**Issue by dhcn** [openethereum/openethereum#522] opened 2021-09-11 09:20 UTC
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:55:20
     |
55   |             extras.insert(util::ident(&ext), |_| panic!("Only one #[extras] attribute can be declared."));
     |                    ^^^^^^ -----------------  ----------------------------------------------------------- supplied 2 arguments
     |                    |
     |                    expected 1 argument
     |
note: associated function defined here

.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:89:23
     |
89   |                 error.insert(variant, |_| panic!("Only one #[error] variant can be declared."));
     |                       ^^^^^^ -------  -------------------------------------------------------- supplied 2 arguments
     |                       |
     |                       expected 1 argument
     |
note: associated function defined here

.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:93:21
     |
93   |                 end.insert(variant, |_| panic!("Only one #[end] variant can be declared."));
     |                     ^^^^^^ -------  ------------------------------------------------------ supplied 2 arguments
     |                     |
     |                     expected 1 argument
     |
note: associated function defined here

**Comment by dhcn** [comment] 2021-09-15 05:26
I find the simple answer：
remove second argument

**Comment by Voklen** [comment] 2021-09-18 17:49
Duplicate of #442

**Comment by Voklen** [comment] 2021-09-20 07:58
By the way could you close this issue due to it being a duplicate and you finding a workaround

**Comment by dhcn** [comment] 2021-09-20 12:13
> By the way could you close this issue due to it being a duplicate and you finding a workaround

Ok，Thank You。

**Closed** 2021-09-20 12:13 UTC
