### ISSUE TITLE
What does "slow state fetch for hash" mean?

### ISSUE THREAD

**Issue by alfy-dev** [openethereum/openethereum#11679] opened 2020-05-05 12:57 UTC
Dear community,
I've searched for an answer, but found nothing satisfactory. Hopefully this will be useful for someone else in the future too.
My parity node is fully synchronized. Now I'm seeing a lot of messages like this:

149 -> GetNodeData:   item 6/384 – slow state fetch for hash 0x034adcb8f82a13f10819d91b94569a46d460514a6b182504584994f414e9c242; took Instant { tv_sec: 337176, tv_nsec: 283787851 }

What does it mean? Can someone explain the context of this? What are the tv_sec and tv_nsec values? What does the 149 mean? The item number? 
My node is running on a root server with SSD disks, my CPUs are used at 75% and RAM 92%. In other words I don't think there is a hardware bottleneck going on. The connexion is also quite good (500 Mbs/s symmetrical).

Thanks!

- **OpenEthereum version**: Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0

- **Operating system**: Linux (debian 9)

- **Installation**: latest release binary, executed with no argument

- **Fully synchronized**: yes

- **Network**: ethereum

- **Restarted**: no

**Comment by adria0** [comment] 2020-05-06 06:55
It literally means that a query took a long time to return. The cause may be one or more of:
- the node is too slow (slow disks likely)
- the node got unlucky and was hit by many fast syncing geth nodes
- the node was busy compacting its db
- the node was busy importing heavy blocks or serving heavy rpcs
- the node just got unlucky and was hit with a slow query but is otherwise fine

**Comment by alfy-dev** [comment] 2020-05-06 14:46
Thank you adria0!

The error messages stopped after a while. No it's been hours since I've haven't seen any. They did not seem to otherwise impact the overall functioning of the node.

So my hypothesis is your number 2). My node was being hit by one or several fast syncing geth nodes, and they are gone now.

I'll leave this issue open for a few more days in case someone wants to explain for posterity the different values in the message.

**Comment by adria0** [comment] 2020-05-06 16:37
Fantastic! We plan to add this question to a FAQ/Troubleshooting section in the future openethereum.org web page (then I will close the issue).

**Closed** 2020-05-14 11:25 UTC
