### ISSUE TITLE
Export state multi-threaded

### ISSUE THREAD

**Issue by marlboroman81** [openethereum/openethereum#11849] opened 2020-08-07 07:05 UTC
- **OpenEthereum version**: 3.0.1
- **Operating system**: Linux Ubuntu 16.04
- **Installation**: one-line installer
- **Fully synchronized**: yes (with -fat-db)
- **Network**: ethereum
- **Restarted**: yes

When I'm doing **export state on the fully synced ethereum node - it takes about 2-3 days to finish** on my linux box (2x 12-core Xeon + 170Gb RAM + SSD Raid). That's because it is single-threaded. It uses only one CPU core.
**Is it possible to make the export-state routine multi-threaded?** (It would finish within 2-4 hours using the same machine)

**Comment by adria0** [comment] 2020-08-07 08:19
Hi @marlboroman81, currently there's no way to do it in multi-thread, and is not scheduled in the current roadmap.
Please, close the issue if you think that the issue is resolved.

**Comment by marlboroman81** [comment] 2020-08-15 07:20
I hope it will be fixed in near future.

**Closed** 2020-08-15 07:19 UTC
