### ISSUE TITLE
Why sync stucks  my node at a specific time

### ISSUE THREAD

**Issue by misaghamouie** [openethereum/openethereum#247] opened 2021-02-02 11:31 UTC
- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Linux
- **Installation**:  built from source
- **Fully synchronized**: yes
- **Network**: ethereum 
can see the problem in the picture below

![12db20e5-3ace-43d2-ab74-9e9cd787b7d6](https://user-images.githubusercontent.com/47473681/106872765-e972e900-66e8-11eb-8b88-d52cc4ec1ed0.jpg)
How to fix this problem

**Comment by rakita** [comment] 2021-02-03 11:14
Not sure, please try with `3.1.1` version

**Comment by ytrezq** [comment] 2021-02-12 00:32
@rakita I’m having the same problem with the latest version too. As soon as I start a new full node without parameters and without prior database directory and config directory, it syncs for a minute and stops.

**Comment by rakita** [comment] 2021-02-12 10:18
@ytrezq can you share full log?

**Comment by ytrezq** [comment] 2021-02-12 11:38
@rakita there s not so much to share. As soon I start Openethereum and just pass tracing=on without config directory, it sync during 20s and stops. No cpu/network/ssd access is used.

I wiped the database and config directory several times but it simply seems Openethereum is no longer able to run from a start.

**Comment by rakita** [comment] 2021-03-16 09:34
Probably duplicate of this: https://github.com/openethereum/openethereum/issues/300

**Closed by rakita** 2021-03-16 09:34 UTC
Labels: user-report
