### ISSUE TITLE
State root of best block header always valid

### ISSUE THREAD

**Issue by plexar88** [openethereum/openethereum#96] opened 2020-11-13 07:29 UTC
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version : OpenEthereum/v3.1.0-stable-2072341-20201102/x86_64-linux-gnu/rustc1.47.0
- **Operating system**: Linux
- **Installation**: https://github.com/openethereum/openethereum/releases/download/v3.1.0/openethereum-linux-v3.1.0.zip
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Thread 'IO Worker #2' panicked at 'State root of best block header always valid.: InvalidStateRoot(0xc9c4d3176e7b19d5f6b378feea89f3d760aab017cd7d45b5abbd5531bdfd1477)', ethcore/src/client/client.rs:1179

**Comment by rakita** [comment] 2020-11-13 09:33
Hi, this looks like #69

**Comment by plexar88** [comment] 2020-11-13 22:16
I removed few last blocks with "_openethereum db reset xx_" and now it start with message "_State root not found for block #11247017 (f6d42a06fcf4dd642d8296e97e346908aaf47507d4ec27fb5ab98a36c4822585)" then stop with error "Thread 'IO Worker #0' panicked at 'State root of best block header always valid.: InvalidStateRoot(0x4a9cd3c47d3a6c8dbbd6461a3a52bbc1628b066aafad612acf5a2a4c39105a57)', ethcore/src/client/client.rs:1179_" How I can fix it without remove db and start synch agan?

**Comment by rakita** [comment] 2020-11-13 23:14
Did you execute 3 and 4th step from here: https://gist.github.com/adria0/1a4505e1823373b03db37a0de5e92b75

**Comment by plexar88** [comment] 2020-11-14 07:42
I got error on step 3: "_Found argument 'experimental-drop-future-blocks' which wasn't expected, or isn't valid in this context_". I compiled it from sources https://github.com/openethereum/openethereum/tree/adria0/dbtools then run .target/release/openethereum  db experimental-drop-future-blocks --base-path path-to-my-blockchain-storage

**Comment by rakita** [comment] 2020-12-04 23:33
Duplicate of #69, fix is made here: https://github.com/openethereum/openethereum/pull/149

**Closed by rakita** 2020-12-04 23:33 UTC
Labels: user-report
