### ISSUE TITLE
[OpenEthereum v3.3.4][mac os] build error

### ISSUE THREAD

**Issue by puffanddmx** [openethereum/openethereum#624] opened 2022-03-08 03:50 UTC
hi

i got the error during the build on mac os M1 chip.

$ cargo build --release --features final

source code : https://github.com/openethereum/openethereum/releases/tag/v3.3.4)
cargo version : cargo 1.59.0 (49d8809dc 2022-02-10)
rustup version : rustup 1.24.3 (ce5817a94 2021-05-31)

```
error: failed to run custom build command for `ring v0.14.6`

Caused by:
  process didn't exit successfully: `/Users/openethereum-3.3.4/target/release/build/ring-eaceec08d140cb6e/build-script-build` (exit status: 101)
```

**Comment by ziogaschr** [comment] 2022-03-09 08:23
Duplicate of https://github.com/openethereum/openethereum/issues/415

**Closed** 2022-03-28 05:37 UTC
