### ISSUE TITLE
Thread 'Verifier #8' panicked at 'attempted to leave type `linked_hash_map:(...)` uninitialized, which is invalid'

### ISSUE THREAD

**Issue by marek-obuchowicz** [openethereum/openethereum#119] opened 2020-11-23 17:25 UTC
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: OpenEthereum/v3.1.0-rc1-stable-ee2b16dfe-20201112/x86_64-macos/rustc1.49.0-beta.1
- **Operating system**: MacOS
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

Trying to start client just after building the sources, it throws an exception on initialization:
```
2020-11-23 18:22:17  Starting OpenEthereum/v3.1.0-rc1-stable-ee2b16dfe-20201112/x86_64-macos/rustc1.49.0-beta.1
2020-11-23 18:22:17  Keys path /Users/elephant/Library/Application Support/OpenEthereum/keys/ethereum
2020-11-23 18:22:17  DB path /Users/elephant/Library/Application Support/OpenEthereum/chains/ethereum/db/906a34e69aec8c0d
2020-11-23 18:22:17  State DB configuration: fast
2020-11-23 18:22:17  Operating mode: active
2020-11-23 18:22:17  Configured for Ethereum using Ethash engine
2020-11-23 18:22:17  Listening for new connections on 127.0.0.1:8546.
2020-11-23 18:22:17  Updated conversion rate to Ξ1 = US$597.26 (7972917 wei/gas)
2020-11-23 18:22:22  Public node URL: enode://d564f35ccf6d3a178dcf8d371ae(...)@x.x.x.x:30303
2020-11-23 18:22:24  Panic occured, see stderr for details


====================

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: panic_hook::set_with::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: lru_cache::LruCache<K,V,S>::insert
  10: ethcore::state_db::StateDB::sync_cache
  11: ethcore::client::client::Importer::import_verified_blocks
  12: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  13: ethcore_io::service_mio::IoChannel<Message>::send_sync
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: std::sys::unix::thread::Thread::new::thread_start
  17: _pthread_start


Thread 'Verifier #4' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H160, std::option::Option<state::account::Account>>` uninitialized, which is invalid', /rustc/21dea46d8347c8b4117c5567949703f0fbb51649/library/core/src/mem/mod.rs:659

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2020-11-23 18:22:24  Finishing work, please wait...
2020-11-23 18:22:24  Block import failed for #2 (0xb495…98c9): Parent not found (0x88e9…6cb6)
2020-11-23 18:22:24
Bad block detected: Error(Msg("Parent not found"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
RLP: f9021df90218a088e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794dd2f1e6e498202e86d8f5442af596580a4f03c2ca04943d941637411107494da9ec8bc04359d731bfd08b72b4d0edcbd4cd2ecb341a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008503ff00100002821388808455ba4241a0476574682f76312e302e302d30636463373634372f6c696e75782f676f312e34a02f0790c5aa31ab94195e1f6443d645af5b75c46c04fbf9911711198a0ce8fdda88b853fa261a86aa9ec0c0
Header: Header { parent_hash: 0x88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6, timestamp: 1438270017, number: 2, author: 0xdd2f1e6e498202e86d8f5442af596580a4f03c2c, transactions_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [71, 101, 116, 104, 47, 118, 49, 46, 48, 46, 48, 45, 48, 99, 100, 99, 55, 54, 52, 55, 47, 108, 105, 110, 117, 120, 47, 103, 111, 49, 46, 52], state_root: 0x4943d941637411107494da9ec8bc04359d731bfd08b72b4d0edcbd4cd2ecb341, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 5000, difficulty: 17163096064, seal: [[160, 47, 7, 144, 197, 170, 49, 171, 148, 25, 94, 31, 100, 67, 214, 69, 175, 91, 117, 196, 108, 4, 251, 249, 145, 23, 17, 25, 138, 12, 232, 253, 218], [136, 184, 83, 250, 38, 26, 134, 170, 158]], hash: Some(0xb495a1d7e6663152ae92708da4843337b958146015a2802f4193a410044698c9) }
Uncles:
Transactions:

2020-11-23 18:22:24  Panic occured, see stderr for details


====================

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: panic_hook::set_with::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: lru_cache::LruCache<K,V,S>::insert
  10: ethcore::client::bad_blocks::BadBlocks::report
  11: ethcore::client::client::Importer::import_verified_blocks
  12: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  13: ethcore_io::service_mio::IoChannel<Message>::send_sync
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: std::sys::unix::thread::Thread::new::thread_start
  17: _pthread_start


Thread 'Verifier #8' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H256, (verification::queue::kind::blocks::Unverified, std::string::String)>` uninitialized, which is invalid', /rustc/21dea46d8347c8b4117c5567949703f0fbb51649/library/core/src/mem/mod.rs:659

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2020-11-23 18:22:24  Panic occured, see stderr for details


====================

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: panic_hook::set_with::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: <ethcore::verification::queue::VerificationQueue<K> as core::ops::drop::Drop>::drop
  10: core::ptr::drop_in_place
  11: core::ptr::drop_in_place
  12: alloc::sync::Arc<T>::drop_slow
  13: alloc::sync::Arc<T>::drop_slow
  14: alloc::sync::Arc<T>::drop_slow
  15: alloc::sync::Arc<T>::drop_slow
  16: <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop
  17: alloc::sync::Arc<T>::drop_slow
  18: core::ptr::drop_in_place
  19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  20: tokio_threadpool::worker::Worker::run_task
  21: tokio_threadpool::worker::Worker::run
  22: tokio_reactor::with_default
  23: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: std::sys::unix::thread::Thread::new::thread_start
  27: _pthread_start


Thread 'event.loop0' panicked at 'Propagating verifier thread panic on shutdown: Any', /Users/elephant/Documents/Workspace/code/kore/ether/openethereum/ethcore/src/verification/queue/mod.rs:853

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


Error: 1
```

**Comment by palkeo** [comment] 2020-11-23 19:44
I feel you. I spent hours on the same problem. This is a duplicate of #120

**Closed** 2020-11-24 09:37 UTC
Labels: duplicate
