### ISSUE TITLE
Error in parity_pendingTransactions

### ISSUE THREAD

**Issue by coinuma-dev** [openethereum/openethereum#334] opened 2021-03-22 21:11 UTC
- **OpenEthereum version (>=3.1.0)**: 3.2.1
- **Operating system**: Linux
- **Installation**: Release binary
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

The result of calling parity_pendingTransactions with filters is:
`{'code': -32602, 'message': 'Invalid parameters: Expected from 0 to 1 parameters.', 'data': '"Got: 2"'}`

[The docs](https://openethereum.github.io/JSONRPC-parity-module#parity_pendingtransactions) say filtering transactions it possible using this method.

**Comment by bnd170** [comment] 2021-03-22 21:39
Same problem here, please provide any fix as soon as possible.

**Comment by rakita** [comment] 2021-03-22 22:12
Duplicate of https://github.com/openethereum/openethereum/issues/159 
change is merged in `dev` branch

**Closed by rakita** 2021-03-22 22:12 UTC
